In [19]:
import numpy as np
import pandas as pd
import tensorflow as tf
import json

In [20]:
df = pd.read_csv('results.csv')
df

results/parsed_code  \
0   \t18 ClassDeclaration\r\n\t\t18 BaseList\r\n\t...   
1   \t18 ClassDeclaration\r\n\t\t18 BaseList\r\n\t...   
2   \t18 ClassDeclaration\r\n\t\t18 BaseList\r\n\t...   
3   \t16 ClassDeclaration\r\n\t\t16 BaseList\r\n\t...   
4   \t16 ClassDeclaration\r\n\t\t16 BaseList\r\n\t...   
5   \t9 ClassDeclaration\r\n\t\t9 BaseList\r\n\t\t...   
6   \t5 ClassDeclaration\r\n\t\t5 BaseList\r\n\t\t...   
7   \t10 ClassDeclaration\r\n\t\t10 BaseList\r\n\t...   
8   \t9 ClassDeclaration\r\n\t\t9 BaseList\r\n\t\t...   
9   \t9 ClassDeclaration\r\n\t\t9 BaseList\r\n\t\t...   
10  \t9 ClassDeclaration\r\n\t\t9 BaseList\r\n\t\t...   
11  \t7 ClassDeclaration\r\n\t\t7 BaseList\r\n\t\t...   
12  \t6 ClassDeclaration\r\n\t\t6 BaseList\r\n\t\t...   

                                 results/parsed_smell  \
0   \r\n\t18 ClassDeclaration\r\n\t\t18 BaseList\r...   
1   \r\n\t\t25 FieldDeclaration\r\n\t\t\t25 Variab...   
2   \r\n\t\t\t\t\t\t74 LocalDeclarationStatement\r...   
3   \r\n\t16 ClassDeclaration\r\n\t\t16 BaseList\r...   
4   \r\n\t\t19 FieldDeclaration\r\n\t\t\t19 Variab...   
5   \r\n\t9 ClassDeclaration\r\n\t\t9 BaseList\r\n...   
6   \r\n\t5 ClassDeclaration\r\n\t\t5 BaseList\r\n...   
7   \r\n\t10 ClassDeclaration\r\n\t\t10 BaseList\r...   
8   \r\n\t9 ClassDeclaration\r\n\t\t9 BaseList\r\n...   
9                                                 NaN   
10  \r\n\t\t71 MethodDeclaration\r\n\t\t\t71 Prede...   
11  \r\n\t7 ClassDeclaration\r\n\t\t7 BaseList\r\n...   
12  \r\n\t6 ClassDeclaration\r\n\t\t6 BaseList\r\n...   

                                        results/smell  
0   Rename class 'K8sClientService' to match pasca...  
1   Remove the field '_configuration' and declare ...  
2   Forward the 'cancellationToken' parameter to t...  
3   Rename class 'K8sEnvironmentFactory' to match ...  
4   Remove this unread private field '_containerId...  
5   Rename class 'K8sEnvironmentFetcher' to match ...  
6   Rename class 'K8sEnvironmentHolder' to match p...  
7   Rename class 'K8sInfoBackgroundService' to mat...  
8   Rename class 'K8sInfoBootstrap' to match pasca...  
9   Complete the task associated to this 'TODO' co...  
10  Add the default parameter value defined in the...  
11  Rename class 'K8sInfoService' to match pascal ...  
12  Rename class 'K8sInfoServiceStub' to match pas...

In [21]:
# Extract the data from the first two columns
col1 = df['results/parsed_code']
col2 = df['results/parsed_smell']

# Create two new dataframes, one for each of the extracted columns
df1 = pd.DataFrame({'parsed_code': col1})
df2 = pd.DataFrame({'parsed_smell': col2})

In [22]:
df1.to_csv('parsed_code.csv', index=False)

df2 = df2.drop(9) # ENaN
df2.to_csv('parsed_smell.csv', index=False)

In [23]:
df = pd.read_csv('parsed_code.csv')
df

parsed_code
0   \t18 ClassDeclaration\r\n\t\t18 BaseList\r\n\t...
1   \t18 ClassDeclaration\r\n\t\t18 BaseList\r\n\t...
2   \t18 ClassDeclaration\r\n\t\t18 BaseList\r\n\t...
3   \t16 ClassDeclaration\r\n\t\t16 BaseList\r\n\t...
4   \t16 ClassDeclaration\r\n\t\t16 BaseList\r\n\t...
5   \t9 ClassDeclaration\r\n\t\t9 BaseList\r\n\t\t...
6   \t5 ClassDeclaration\r\n\t\t5 BaseList\r\n\t\t...
7   \t10 ClassDeclaration\r\n\t\t10 BaseList\r\n\t...
8   \t9 ClassDeclaration\r\n\t\t9 BaseList\r\n\t\t...
9   \t9 ClassDeclaration\r\n\t\t9 BaseList\r\n\t\t...
10  \t9 ClassDeclaration\r\n\t\t9 BaseList\r\n\t\t...
11  \t7 ClassDeclaration\r\n\t\t7 BaseList\r\n\t\t...
12  \t6 ClassDeclaration\r\n\t\t6 BaseList\r\n\t\t...

In [24]:
df = pd.read_csv('parsed_smell.csv')
df

parsed_smell
0   \r\n\t18 ClassDeclaration\r\n\t\t18 BaseList\r...
1   \r\n\t\t25 FieldDeclaration\r\n\t\t\t25 Variab...
2   \r\n\t\t\t\t\t\t74 LocalDeclarationStatement\r...
3   \r\n\t16 ClassDeclaration\r\n\t\t16 BaseList\r...
4   \r\n\t\t19 FieldDeclaration\r\n\t\t\t19 Variab...
5   \r\n\t9 ClassDeclaration\r\n\t\t9 BaseList\r\n...
6   \r\n\t5 ClassDeclaration\r\n\t\t5 BaseList\r\n...
7   \r\n\t10 ClassDeclaration\r\n\t\t10 BaseList\r...
8   \r\n\t9 ClassDeclaration\r\n\t\t9 BaseList\r\n...
9   \r\n\t\t71 MethodDeclaration\r\n\t\t\t71 Prede...
10  \r\n\t7 ClassDeclaration\r\n\t\t7 BaseList\r\n...
11  \r\n\t6 ClassDeclaration\r\n\t\t6 BaseList\r\n...

In [25]:
import numpy as np

# Define sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define derivative of sigmoid activation function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define backpropagation function
def backpropagation(X, y, learning_rate, epochs):
    # Initialize random weights for input layer
    weights_input = np.random.random((X.shape[1], 4))
    # Initialize random weights for hidden layer
    weights_hidden = np.random.random((4, 1))

    for i in range(epochs):
        # Forward propagation
        hidden_layer_input = np.dot(X, weights_input)
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden)
        output_layer_output = sigmoid(output_layer_input)

        # Backpropagation
        output_error = y - output_layer_output
        output_delta = output_error * sigmoid_derivative(output_layer_output)
        hidden_error = output_delta.dot(weights_hidden.T)
        hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

        # Update weights
        weights_hidden += hidden_layer_output.T.dot(output_delta) * learning_rate
        weights_input += X.T.dot(hidden_delta) * learning_rate

    return weights_input, weights_hidden

# Test the backpropagation function
X = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
y = np.array([[0], [1], [1], [0]])
weights_input, weights_hidden = backpropagation(X, y, 0.1, 10000)
print(weights_input)
print(weights_hidden)

[[ 2.83465333  6.3486957   2.56473505  0.99257283]
 [-1.18499528  5.77764152  3.86138662  0.80415195]
 [ 1.05126083 -2.50770176 -4.77713157 -0.68456269]]
[[-3.38481086]
 [ 8.65806685]
 [-7.20618316]
 [-2.95242288]]
